use make conditional syntax variant

diff --git a/kubeflow/Makefile b/kubeflow/Makefile
--- a/kubeflow/Makefile
+++ b/kubeflow/Makefile
@@ -33,10 +33,13 @@ MANIFESTS_URL=https://github.com/kubeflow/manifests.git@master
 # Validate cluster values are changed from default dummy values
 .PHONY: validate-values
 validate-values:
-	@if [ $(MGMTCTXT) == "MANAGEMENT-CTXT" ] || [ $(NAME) == "KUBEFLOW-NAME" ] || [ $(LOCATION) == "LOCATION" ] || [ $(PROJECT) == "PROJECT" ]; then\
-		echo "[ERROR] either of MGMTCTXT, NAME, LOCATION, PROJECT values not set.";\
-		exit 1;\
-    fi
+ifeq ($(shell test "$(MGMTCTXT)" =  MANAGEMENT-CTXT  -o  \
+                   "$(NAME)"     =  KUBEFLOW-NAME  -o  \
+                   "$(LOCATION)" =  LOCATION  -o  \
+                   "$(PROJECT)"  =  PROJECT  &&  printf "true"), true)
+	@echo "[ERROR] either of MGMTCTXT, NAME, LOCATION, PROJECT values not set."
+	@exit 1;
+endif
 
 #************************************************************************************************************************
 #
diff --git a/management/Makefile b/management/Makefile
--- a/management/Makefile
+++ b/management/Makefile
@@ -21,10 +21,13 @@ echo-ctxt:
 # Validate cluster values are changed from default dummy values
 .PHONY: validate-values
 validate-values:
-	@if [ $(NAME) == "NAME" ] || [ $(LOCATION) == "LOCATION" ] || [ $(PROJECT) == "PROJECT" ]; then\
-        echo "[ERROR] either of NAME, LOCATION, PROJECT values not set.";\
-		exit 1;\
-    fi
+ifeq ($(shell test "$(NAME)"     =  NAME  -o  \
+                   "$(LOCATION)" =  LOCATION  -o  \
+                   "$(PROJECT)"  =  PROJECT  &&  printf "true"), true)
+	@echo "[ERROR] either of NAME, LOCATION, PROJECT values not set."
+	@exit 1;
+endif
+
 
 # Get packages
 # TODO(jlewi): We should think about how we layout packages in kubeflow/manifests so
